apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: blog-route
  namespace: blog
spec:
  parentRefs:
    - name: web-gateway
      namespace: gateway # Gateway가 있는 ns
      sectionName: http-blog
    - name: web-gateway
      namespace: gateway # Gateway가 있는 ns
      sectionName: https-blog
  hostnames:
    - blog.sonhs.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: son-blog
          port: 80
